<?php
// URL BASE PARAL LINKAR IMAGENS E ESTILOS
// PEGA O PROTOCOLO + NOME DO SERVIDOR + URL REQUISITADA + QUERY
$BASE_URL = "http://" . $_SERVER['SERVER_NAME'] . dirname($_SERVER['REQUEST_URI']. '?') . '/';
